import pygame as pg
import math

RES = WIDTH, HEIGHT = 1600, 900
FPS = 63
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

LOGO_NAME = 'resources/logo.png'

MAPNAME = 'map1.txt'
MAPSDIR = 'maps'
TILESIZE = 50

PLAYER_HEALTH = 100
HEALTH_BAR_COLOR = 'red'
HEALTH_BAR_DIST = 5
HEALTH_BAR_WIDTH = 50
HEALTH_BAR_HEIGHT = 30
HEALTH_TEXT_COLOR = 'white'

PLAYER_POS = 1.2, 1.2  # MiniMap coordinates
PLAYER_ANG = 0
PLAYER_SPD = 0.004
PLAYER_ANG_VEL = 0.002
PLAYER_SIZE_SCALE = 40

MOUSE_SENSITIVITY = 0.00025
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 50
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT
MOUSE_BORDER_UP = 100
MOUSE_BORDER_DOWN = HEIGHT - MOUSE_BORDER_UP

FOV = math.pi / 2.5
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANG = FOV / NUM_RAYS
MAX_DEPTH = int(math.sqrt((WIDTH/TILESIZE) ** 2 + (HEIGHT/TILESIZE) ** 2))

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

#Textures
TEXTURES_DIR = 'resources/textures/'
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

AIM_BAR_COLOR = 'green'

SPRITE_PATH = "resources/sprites/static/0.png"

# Settings menu settings
SENSITIVITY_SLIDER_POS = 100, 100
MAX_SENSITIVITY =  0.0003
MIN_SENSITIVITY = 0.0001
SENSITIVITY_SLIDER_STEP = 0.00001
SENSITIVITY_TEXT_POS = 100, 50
SENSITIVITY_TEXT_SIZE = 10, 10

# Keys
FORWARD_KEY = pg.K_w
BACKWARDS_KEY = pg.K_s
LEFT_KEY = pg.K_a
RIGHT_KEY = pg.K_d

ROT_LEFT_KEY = pg.K_LEFT
ROT_RIGHT_KEY = pg.K_RIGHT